### ISSUE TITLE
Consider moving to crate instead of binary

### ISSUE THREAD

**Issue by madmaxio** [legolord208/insult#1]
Hello, have you considered to make this as a crate? For some web integration and stuff.

**Comment by jD91mZM2** [comment]
I have considered it, but I've never cared to do it. Will do immediately, hold on.

**Comment by jD91mZM2** [comment]
Fixed in [3152b](https://github.com/jD91mZM2/insult/commit/3152bf62dcebc701c7c3675f688e24a0e0a44813).

Also added an example to the README.
Sadly the crate requires `failure` and `xdg`, both which are actually only needed for the binary. (This is because of https://github.com/rust-lang/cargo/issues/1982)
